// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsQAF_v-cpeAc_55NkrXU7oZ5q__gXs94',
    appId: '1:708718855301:web:b1e3f76781d96ad5a515ec',
    messagingSenderId: '708718855301',
    projectId: 'perfect-flatmates',
    authDomain: 'perfect-flatmates.firebaseapp.com',
    storageBucket: 'perfect-flatmates.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfuQnRUiY7YQ2XVI-mgnfCv8--agTem6U',
    appId: '1:708718855301:android:fe8a1c00a6bc7c6fa515ec',
    messagingSenderId: '708718855301',
    projectId: 'perfect-flatmates',
    storageBucket: 'perfect-flatmates.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhDUkiU6J1ZIF2DSpQQLhFod-vcNvKdQo',
    appId: '1:708718855301:ios:b55d9eb5f2be95b1a515ec',
    messagingSenderId: '708718855301',
    projectId: 'perfect-flatmates',
    storageBucket: 'perfect-flatmates.appspot.com',
    iosClientId: '708718855301-6hpbpo3il06bu0oieckpnf9n8imgk7st.apps.googleusercontent.com',
    iosBundleId: 'com.example.perfectFlatmate',
  );
}
